sudo: required
dist: trusty

language: go
go_import_path: github.com/hyperhq/runv

matrix:
  include:
    - go: 1.7

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq autoconf automake pkg-config libdevmapper-dev libvirt-dev libvirt-bin wget libaio1 libpixman-1-0
  - wget https://s3-us-west-1.amazonaws.com/hypercontainer-download/qemu-hyper/qemu-hyper_2.4.1-1_amd64.deb && sudo dpkg -i --force-all qemu-hyper_2.4.1-1_amd64.deb
  - git clone https://github.com/hyperhq/hyperstart.git ${GOPATH}/src/github.com/hyperhq/hyperstart

# override the default `install`, otherwise default `install` will export ${TRAVIS_BUILD_DIR}/Godeps/_workspace as GOPATH
# see https://docs.travis-ci.com/user/languages/go#Dependency-Management

install:
  - cd ${TRAVIS_BUILD_DIR}
  - hack/verify-gofmt.sh
  - hack/validate-vet.sh
  - ./autogen.sh && ./configure && make && sudo GOPATH=${GOPATH} PATH=${PATH} GOROOT=${GOROOT} make install

script:
  - cd ${TRAVIS_BUILD_DIR} && sudo GOPATH=${GOPATH} PATH=${PATH} GOROOT=${GOROOT} hack/test-cmd.sh
